#!/usr/bin/env python3
"""Audit saved records and source corrections; --write regenerates paper totals.

Without --write, fail if the LaTeX summary is stale. Checks validate arithmetic
and provenance structure, not eligibility or correctness of classifications.
"""
import argparse
import collections
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# `from lit_search import on_topic` relies on the script's own directory being
# on sys.path. CPython adds it only when the interpreter is started without
# isolation; under `python -I`, `python -P`, or PYTHONSAFEPATH=1 it does not,
# and the import fails with ModuleNotFoundError however the script is invoked.
# Add it explicitly so the audit runs from any working directory.
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
from lit_search import on_topic  # noqa: E402  (needs the sys.path line above)
ORDER = ["A_GEN_CHECKED", "B_GEN_PROOF", "C_LLM_AS_ORACLE",
         "D_FORMAL_HELPS_LLM", "E_RUNTIME", "F_ASSURANCE", "G_OTHER"]
NAMES = ["Generate and check", "Generate and prove",
         "Model / empirical / unresolved", "Formalism serves the model",
         "Runtime", "Assurance-oriented", "Residual"]


def load_records():
    """Return (snapshot, corrected_snapshot, corrections, supplementary).

    The file holds TWO populations and they must not be pooled. The arXiv
    snapshot is the counted denominator: every record in it passed the
    generative-model AND formal-tool lexical filter, and the A-G percentages
    describe it. Supplementary records (source="scholar") are added during
    revision from targeted searching; they are cited in the prose but are NOT
    in the denominator, because they were not drawn by the same query and in
    general do not satisfy the same filter -- ACCESS, for instance, is
    pre-LLM assurance-case work with no generative-model content at all.
    Pooling them would inflate the assurance count with background literature
    and make the ratio a comparison across two different populations.
    """
    everything = json.loads((HERE / "corpus_labelled.json").read_text())
    supplementary = [r for r in everything if r.get("source") == "scholar"]
    records = [r for r in everything if r.get("source") != "scholar"]
    ids = [r["id"].split("v")[0] for r in records]
    assert len(ids) == len(set(ids)), "Duplicate version-independent arXiv IDs"
    assert all(on_topic(r) for r in records), "Saved record fails repaired lexical filter"
    assert all(r["class"] in ORDER for r in everything), "Unknown class"
    supp_ids = {r["id"] for r in supplementary}
    assert len(supp_ids) == len(supplementary), "Duplicate supplementary records"
    assert not (supp_ids & set(ids)), "Record appears in both populations"
    corrections = json.loads((HERE / "label_corrections.json").read_text())
    assert len({c["id"] for c in corrections}) == len(corrections)
    corrected = {i: dict(r) for i, r in zip(ids, records)}
    for c in corrections:
        row = corrected[c["id"]]
        assert row["class"] == c["previous_class"], "Correction no longer matches snapshot"
        assert c["source"].startswith("https://") and c["location"] and c["reason"]
        row.update({k: c[k] for k in ("class", "checker")})
    return records, list(corrected.values()), corrections, supplementary


def summary_tex(records, corrected, corrections, supplementary=()):
    counts = collections.Counter(r["class"] for r in corrected)
    years = collections.Counter(r["date"][:4] for r in records)
    values = {"CorpusN": len(records), "CorpusCorrections": len(corrections),
              "CorpusSupplementary": len(supplementary)}
    values.update({f"Corpus{letter}": counts[key]
                   for letter, key in zip("ABCDEFG", ORDER)})
    values.update({"CorpusAB": counts[ORDER[0]] + counts[ORDER[1]],
                   "CorpusYearTwentyFive": years["2025"],
                   "CorpusYearTwentySix": years["2026"]})
    return ("% Generated by literature/check_counts.py --write; counts are provisional.\n"
            + "".join("\\newcommand{\\" + k + "}{" + str(v) + "}\n"
                      for k, v in values.items()))


def figure(records, corrected):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    raw = collections.Counter(r["class"] for r in records)
    cur = collections.Counter(r["class"] for r in corrected)
    years = collections.Counter(r["date"][:4] for r in records)
    fig, (ax, ay) = plt.subplots(1, 2, figsize=(9, 3.7),
                               gridspec_kw={"width_ratios": [1.8, 1]})
    ax.barh(NAMES, [cur[k] for k in ORDER], color="#376b8c")
    ax.invert_yaxis()
    for i, k in enumerate(ORDER):
        delta = f" (was {raw[k]})" if cur[k] != raw[k] else ""
        ax.text(cur[k] + 2, i, f"{cur[k]}{delta}", va="center", fontsize=8)
    ax.set_xlim(0, max(cur.values()) + 65)
    ax.set_xlabel("Records after two documented corrections")
    ax.set_title("(a) Provisional primary labels", loc="left", fontsize=10)
    dates = [str(y) for y in range(2020, 2027)]
    ay.bar(dates, [years[y] for y in dates], color="#376b8c")
    for i, y in enumerate(dates):
        ay.text(i, years[y] + 2, str(years[y]), ha="center", fontsize=8)
    ay.tick_params(axis="x", labelrotation=45)
    ay.set_ylim(0, max(years.values()) * 1.15)
    ay.set_ylabel("Saved records")
    ay.set_title("(b) Submission year\n(2026 partial)", loc="left", fontsize=10)
    for a in (ax, ay):
        a.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    figures = ROOT / "paper/figures" if (ROOT / "paper/figures").is_dir() else ROOT / "figures"
    fig.savefig(figures / "literature_taxonomy.png", dpi=300)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    records, corrected, corrections, supplementary = load_records()
    expected = summary_tex(records, corrected, corrections, supplementary)
    # Online Resource 2 retains the flat `sections/` layout when extracted;
    # the shared repository keeps its authoring source under `paper/sections/`.
    paper_sections = ROOT / "paper/sections"
    target = (paper_sections if paper_sections.is_dir() else ROOT / "sections") / "00-corpus-summary.tex"
    if args.write:
        target.write_text(expected)
        figure(records, corrected)
    assert target.read_text() == expected, "Stale summary: rerun with --write"
    print("Collection file SHA-256:", hashlib.sha256((HERE / "corpus_labelled.json").read_bytes()).hexdigest())
    print("Records:", len(records), "| unique IDs and repaired filters: OK")
    print("Corrections with source locators:", len(corrections))
    print("Corrected classes:", dict(collections.Counter(r["class"] for r in corrected)))
    print("First-submission years:", dict(sorted(collections.Counter(r["date"][:4] for r in records).items())))
    print("LaTeX summary: matches; classification validity remains unestablished.")


if __name__ == "__main__":
    main()
